title: Holger's Guidebook 
description: This webpage contains additional content with source code to all sessions.
theme: just-the-docs

color_scheme: light

url: 

aux_links:
  "Holger's ğŸ“˜": 
    - "https://flixengineering.com/books"
  "ğŸ¥ Courses":
    - "https://courses.landgraf.dev/"
  "ğŸ’› Thank you â˜•ï¸":
    - "https://ko-fi.com/holgerflick"

aux_links_new_tab: true

callouts:
  warning:
    title: warning
    color: red

  note:
    title: note
    color: yellow
